# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hww85oZXG9yrIaxudUlUyOtnWtGptJE_
"""

greeting = "Hello Data Engineering"
print(greeting)

int_var = 8
float_var = 10.0
str_var = "Hello"
bool_var = True

print(int_var)
print(str_var)
print(float_var)
print(bool_var)

"""Mathematical Operators"""

num1 = 7
num2 = 10

sum = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num2 / num1

print(sum)
print(sub)
print(mul)
print(div)

"""Comparison Operators"""

var_equal = num1 == num2
print(var_equal)

not_equal = num1 != num2
print(not_equal)

greater_equal = num1 > num2
print(greater_equal)

less_equal = num1 < num2
print(less_equal)

greater = num1 >= num2
print(greater)

less = num1 <= num2
print(less)

"""Logical Operators"""

print(True and False)
print(True or False)
print(True and True)

"""Control Statements

If Statements |
For Loops |
While Loops
"""

num = 7

if num > 10:
    print("Number is greater than 10")
elif num < 10:
    print("Number is less than 10")
else:
    print("Number is equal to 10")

for i in range(5):
  print(i)

for j in range(1, 10 , 2):
  print(j)

number = 5

while number >= 0:
  print(number)
  number -= 1

"""Functions in Python"""

def func1():
  print("Hello World")

func1()

def greet(name):
  print("Hello " + name)

greet("Suhas")

def num(number):
  print(number * 2)

num(5)

def add(num1, num2):
  return num1 + num2

ad = add(5,6)
print(ad)

def mul_num(n1, n2):
  return n1 * n2

mul = mul_num(3, 2)
print(mul)

"""Modules in Python

- Python files
- Define functions, classes, variables
- Import into your code to use
"""

import math

print(math.sqrt(16))

"""Packages in Python

- Organize the code files
- To use package, installation needed
- Way to share code

To install package - !pip install package_name
"""

!pip install pandas

import pandas as pd

data = {'name':["suhas","nani","tata"], 'Age': [24, 25, 26]}

df = pd.DataFrame(data)
print(df)

"""String Manipulation

- Sequence of characters
- They can be letters, numbers, symbols

"""

greeting = "Hello Data Engineering"

print(greeting)

fname =  "Suhas "
lname = "sivakumar"

fullname = fname + lname

print(fullname)

newString = greeting.replace("Hello", "Hi")
print(newString)

strip = "          Suhas          "
print(strip.strip())

index = greeting.find('Data')
print(index)

format_val = "hello {}"
print(format_val.format("Suhas"))